/**
 * Échantillon de diagnostics CIM-10 (libellés et synonymes FR courants).
 * En production, remplacer ou enrichir par un référentiel officiel (ATIH / WHO).
 */
export const icdEntries = [
  { code: 'I10', label: 'Hypertension essentielle (primitive)', synonyms: ['hypertension artérielle', 'hta', 'hypertendu', 'hypertension'] },
  { code: 'I11.9', label: 'Maladie cardiaque hypertensive sans insuffisance cardiaque', synonyms: ['cardiopathie hypertensive'] },
  { code: 'I20.9', label: 'Angine de poitrine, sans précision', synonyms: ['angor', 'angine de poitrine', 'douleur thoracique angineuse'] },
  { code: 'I21.9', label: 'Infarctus aigu du myocarde, sans précision', synonyms: ['infarctus', 'iam', 'idm', 'crise cardiaque'] },
  { code: 'I25.1', label: 'Maladie athérosclérotique du cœur', synonyms: ['coronaropathie', 'maladie coronarienne', 'sténose coronaire'] },
  { code: 'I48.0', label: 'Fibrillation auriculaire paroxystique', synonyms: ['fibrillation auriculaire', 'fibrillation auriculaire paroxystique', 'arythmie auriculaire'] },
  { code: 'I50.0', label: 'Insuffisance cardiaque congestive', synonyms: ['insuffisance cardiaque', 'icc', 'œdème pulmonaire cardiogénique'] },
  { code: 'I63.9', label: 'Infarctus cérébral, sans précision', synonyms: ['accident vasculaire cérébral', 'avc', 'ictus ischémique'] },
  { code: 'I64', label: 'Accident vasculaire cérébral, non précisé comme hémorragique ou ischémique', synonyms: ['avc', 'accident vasculaire'] },
  { code: 'E11.9', label: 'Diabète sucré de type 2 sans complication', synonyms: ['diabète type 2', 'dt2', 'diabète insulinorésistant'] },
  { code: 'E11.65', label: 'Diabète sucré de type 2 avec hyperglycémie', synonyms: ['hyperglycémie diabétique'] },
  { code: 'E10.9', label: 'Diabète sucré de type 1 sans complication', synonyms: ['diabète type 1', 'dt1', 'diabète insulinodépendant'] },
  { code: 'E78.5', label: 'Hyperlipidémie, sans précision', synonyms: ['hypercholestérolémie', 'dyslipidémie', 'hyperlipidémie'] },
  { code: 'E03.9', label: 'Hypothyroïdie, sans précision', synonyms: ['hypothyroïdie', 'thyroïde paresseuse'] },
  { code: 'E05.9', label: 'Thyrotoxicose, sans précision', synonyms: ['hyperthyroïdie', 'basedow'] },
  { code: 'J44.1', label: 'BPCO avec exacerbation aiguë', synonyms: ['bronchopneumopathie obstructive', 'bpco', "poumon d'emphysème"] },
  { code: 'J44.9', label: 'BPCO, sans précision', synonyms: ['bpco', 'bronchopneumopathie chronique'] },
  {
    code: 'J18.9',
    label: 'Pneumonie, sans précision',
    synonyms: [
      'pneumonie',
      'infection pulmonaire',
      'pneumopathie',
      'pneumopatgie',
      'pneumonie aigue',
      'pneumopathie infectieuse',
    ],
  },
  {
    code: 'J96.0',
    label: 'Insuffisance respiratoire aiguë, type I (hypoxémie sans hypercapnie)',
    synonyms: [
      'insuffisance respiratoire aigue',
      'insuffisance respiratoire aiguë',
      'hypoxemie',
      'hypoxémie',
      'hypoxemiante',
      'hypoxémiante',
      'pneumopathie hypoxemiante',
      'pneumopathie hypoxémiante',
      'pneumopatgie hypoxemiante',
      'pneumopatgie hypoxémiante',
      'detresse respiratoire',
      'détresse respiratoire',
      'sdr',
      'sdrs',
    ],
  },
  {
    code: 'N17.9',
    label: 'Insuffisance rénale aiguë, sans précision',
    synonyms: [
      'insuffisance renale aigue',
      'insuffisance rénale aiguë',
      'insuffisance renale aiguë',
      'ira',
      'ira aigue',
      'dysfonction renale aigue',
      'lésion renale aigue',
    ],
  },
  {
    code: 'R57.2',
    label: 'Choc septique',
    synonyms: ['choc septique', 'choc infectieux', 'septic shock', 'etat de choc septique', 'état de choc septique'],
  },
  {
    code: 'A41.9',
    label: 'Sepsis, sans précision',
    synonyms: ['sepsis', 'septicemie', 'septicémie', 'infection generalisee severe', 'etat septique', 'état septique'],
  },
  { code: 'J06.9', label: 'Infection aiguë des voies respiratoires supérieures', synonyms: ['ivrs', 'rhinopharyngite', 'refroidissement'] },
  { code: 'K21.9', label: 'Reflux gastro-œsophagien sans œsophagite', synonyms: ['rgp', 'reflux gastro-œsophagien', 'brûlures estomac'] },
  { code: 'K29.7', label: 'Gastrite, sans précision', synonyms: ['gastrite'] },
  { code: 'K59.1', label: 'Diarrhée fonctionnelle', synonyms: ['diarrhée', 'trouble fonctionnel intestinal'] },
  { code: 'K80.20', label: 'Calcul de la vésicule sans cholécystite', synonyms: ['lithiase biliaire', 'calcul biliaire', 'colique hépatique'] },
  { code: 'N18.9', label: 'Insuffisance rénale chronique, stade non précisé', synonyms: ['irc', 'insuffisance rénale chronique', 'maladie rénale chronique'] },
  { code: 'N39.0', label: 'Infection des voies urinaires, site non précisé', synonyms: ['infection urinaire', 'ivu', 'cystite'] },
  { code: 'M54.5', label: 'Lombalgie basse', synonyms: ['lombalgie', 'mal de dos', 'douleur lombaire'] },
  { code: 'M79.7', label: 'Fibromyalgie', synonyms: ['fibromyalgie', 'syndrome fibromyalgique'] },
  { code: 'G43.9', label: 'Migraine, sans précision', synonyms: ['migraine', 'céphalée migraineuse'] },
  { code: 'G44.2', label: 'Céphalée de tension', synonyms: ['céphalée de tension', 'mal de tête tension'] },
  { code: 'F32.9', label: 'Épisode dépressif, sans précision', synonyms: ['dépression', 'épisode dépressif'] },
  { code: 'F41.1', label: 'Trouble anxieux généralisé', synonyms: ['tag', 'anxiété généralisée'] },
  { code: 'F41.9', label: 'Trouble anxieux, sans précision', synonyms: ['trouble anxieux', 'anxiété'] },
  { code: 'F43.1', label: 'État de stress post-traumatique', synonyms: ['tspt', 'stress post traumatique'] },
  { code: 'B34.9', label: 'Infection virale, sans précision', synonyms: ['virose', 'infection virale'] },
  { code: 'A09.9', label: 'Gastro-entérite et colite sans précision', synonyms: ['gastro entérite', 'gastro', 'gastro-enterite'] },
  { code: 'L20.9', label: 'Dermatite atopique, sans précision', synonyms: ['eczéma', 'dermatite atopique'] },
  { code: 'L30.9', label: 'Dermatite, sans précision', synonyms: ['dermatite', 'eczéma non spécifié'] },
  { code: 'H10.9', label: 'Conjonctivite, sans précision', synonyms: ['conjonctivite'] },
  { code: 'H66.9', label: 'Otite moyenne, sans précision', synonyms: ['otite', 'infection oreille'] },
  { code: 'R50.9', label: 'Fièvre, sans précision', synonyms: ['fièvre', 'hyperthermie', 'température élevée'] },
  { code: 'R06.0', label: 'Dyspnée', synonyms: ['dyspnée', 'essoufflement', 'difficulté respiratoire'] },
  { code: 'R10.4', label: 'Douleur abdominale, autre et sans précision', synonyms: ['douleur abdominale', 'mal au ventre'] },
  { code: 'R51', label: 'Céphalée', synonyms: ['céphalée', 'mal de tête'] },
  { code: 'R53', label: 'Asthénie', synonyms: ['asthénie', 'fatigue', 'faiblesse générale'] },
  { code: 'Z00.8', label: 'Examen médical général, autres examens', synonyms: ['bilan de santé', 'visite médicale'] },
  { code: 'Z09.8', label: 'Suivi après traitement, autres situations', synonyms: ['suivi post thérapeutique'] },
  { code: 'C34.9', label: 'Tumeur maligne du poumon, sans précision', synonyms: ['cancer du poumon', 'carcinome pulmonaire'] },
  { code: 'C50.9', label: 'Tumeur maligne du sein, sans précision', synonyms: ['cancer du sein', 'carcinome mammaire'] },
  { code: 'C61', label: 'Tumeur maligne de la prostate', synonyms: ['cancer de la prostate', 'adénocarcinome prostatique'] },
  { code: 'D64.9', label: 'Anémie, sans précision', synonyms: ['anémie', 'anémie non spécifiée'] },
  { code: 'D50.9', label: 'Anémie ferriprive, sans précision', synonyms: ['anémie ferriprive', 'carence en fer'] },
  { code: 'S72.0', label: 'Fracture du col du fémur', synonyms: ['fracture col fémoral', 'fracture hanche'] },
  { code: 'T14.9', label: 'Traumatisme, sans précision', synonyms: ['traumatisme', 'blessure non spécifiée'] },
  { code: 'U07.1', label: 'COVID-19, virus identifié', synonyms: ['covid', 'covid-19', 'coronavirus sars-cov-2'] },
  { code: 'F10.2', label: 'Syndrome de dépendance à l’alcool', synonyms: ['alcoolisme', 'dépendance alcoolique'] },
  { code: 'F17.2', label: 'Syndrome de dépendance au tabac', synonyms: ['tabagisme', 'dépendance tabac', 'sevrage tabagique'] },
  { code: 'I67.9', label: 'Maladie cérébrovasculaire, sans précision', synonyms: ['maladie vasculaire cérébrale'] },
  { code: 'G40.9', label: 'Épilepsie, sans précision', synonyms: ['épilepsie', 'crise convulsive'] },
  { code: 'N40', label: 'Hyperplasie de la prostate', synonyms: ['adénome prostatique', 'hypertrophie prostate'] },
  { code: 'K57.32', label: 'Diverticulose du côlon sans perforation ou abcès', synonyms: ['diverticulose', 'diverticules coliques'] },
  { code: 'M17.9', label: 'Gonarthrose, sans précision', synonyms: ['gonarthrose', 'arthrose genou'] },
  { code: 'M19.90', label: 'Arthrose, sans précision', synonyms: ['arthrose', 'arthrite dégénérative'] },
  { code: 'H40.9', label: 'Glaucome, sans précision', synonyms: ['glaucome'] },
  { code: 'E66.9', label: 'Obésité, sans précision', synonyms: ['obésité', 'surpoids sévère'] },
  { code: 'F90.0', label: 'Trouble déficit de l’attention avec hyperactivité', synonyms: ['tdah', 'hyperactivité', 'trouble attention'] },
  { code: 'G47.0', label: 'Insomnie', synonyms: ['insomnie', 'trouble du sommeil'] },
  { code: 'K25.9', label: 'Ulcère gastrique sans hémorragie ni perforation', synonyms: ['ulcère gastrique', 'ulcère estomac'] },
  { code: 'K26.9', label: 'Ulcère duodénal sans hémorragie ni perforation', synonyms: ['ulcère duodénal'] },
  { code: 'J45.9', label: 'Asthme, sans précision', synonyms: ['asthme', 'crise d asthme'] },
  { code: 'B02.9', label: 'Zona sans complication', synonyms: ['zona', 'herpès zoster'] },
  { code: 'A46', label: 'Érysipèle', synonyms: ['érysipèle', 'angine de face'] },
  { code: 'L03.11', label: 'Cellulite aiguë des membres', synonyms: ['cellulite infectieuse', 'infection tissus mous'] },
  { code: 'I83.9', label: 'Varices des membres inférieurs sans ulcère', synonyms: ['varices', 'varices jambes'] },
  { code: 'K92.2', label: 'Hémorragie gastro-intestinale, sans précision', synonyms: ['hémorragie digestive', 'rectorragies', 'méléna'] },
  { code: 'R07.4', label: 'Douleur thoracique, sans précision', synonyms: ['douleur thoracique', 'douleur poitrine'] },
  { code: 'T78.4', label: 'Allergie, sans précision', synonyms: ['allergie', 'réaction allergique'] },
  { code: 'Z95.1', label: 'Présence d’implant cardiaque', synonyms: ['pacemaker', 'stimulateur cardiaque', 'sonde'] },
  { code: 'Z95.5', label: 'Présence d’implant coronaire', synonyms: ['stent coronaire', 'pontage'] },

  /* --- Endocrinologie / métabolisme --- */
  { code: 'E87.1', label: 'Hypo-osmolarité et hyponatrémie', synonyms: ['hyponatremie', 'hyponatrémie', 'natremie basse'] },
  { code: 'E87.5', label: 'Hyperkaliémie', synonyms: ['hyperkaliemie', 'hyperkaliémie', 'potassium eleve'] },
  { code: 'E86', label: 'Déshydratation', synonyms: ['deshydratation', 'déshydratation', 'hypovolemie', 'hypovolémie'] },
  { code: 'E89.0', label: 'Hypothyroïdie après intervention', synonyms: ['hypothyroidie post operatoire'] },
  { code: 'R73.9', label: 'Hyperglycémie, sans précision', synonyms: ['hyperglycemie', 'hyperglycémie', 'glycemie elevee'] },
  { code: 'E16.2', label: 'Hypoglycémie, sans précision', synonyms: ['hypoglycemie', 'hypoglycémie', 'glycemie basse'] },

  /* --- Cardio / vasculaire --- */
  { code: 'I47.2', label: 'Tachycardie ventriculaire', synonyms: ['tachycardie ventriculaire', 'tv', 'arythmie ventriculaire'] },
  { code: 'I49.5', label: 'Syndrome du QT long', synonyms: ['qt long', 'torsades de pointes'] },
  { code: 'I80.1', label: 'Phlébite et thrombophlébite des membres inférieurs', synonyms: ['phlebite', 'phlébite', 'tvp', 'thrombose veineuse profonde', 'trombose veineuse'] },
  { code: 'I26.9', label: 'Embolie pulmonaire sans mention de coeur pulmonaire aigu', synonyms: ['embolie pulmonaire', 'embolie pulmonaire aigue', 'thrombo embolie pulmonaire'] },
  { code: 'I71.4', label: 'Anévrisme et dissection de l’aorte abdominale', synonyms: ['anevrisme aorte', 'anevrisme aortique', 'dissection aortique'] },
  { code: 'I95.1', label: 'Hypotension orthostatique', synonyms: ['hypotension orthostatique', 'malaise orthostatique'] },
  { code: 'I89.0', label: 'Lymphœdème, sans précision', synonyms: ['lymphoedeme', 'lymphœdème', 'œdeme lymphatique'] },

  /* --- Neurologie --- */
  { code: 'G45.9', label: 'Accident ischémique transitoire, sans précision', synonyms: ['ait', 'accident ischemique transitoire', 'micro avc'] },
  { code: 'G93.1', label: 'Lésion cérébrale anoxique', synonyms: ['anoxie cerebrale', 'encéphalopathie hypoxique'] },
  { code: 'G35', label: 'Sclérose en plaques', synonyms: ['sclerose en plaques', 'sep'] },
  { code: 'G20', label: 'Maladie de Parkinson', synonyms: ['parkinson', 'maladie parkinson'] },
  { code: 'G30.9', label: 'Maladie d’Alzheimer, sans précision', synonyms: ['alzheimer', 'demence alzheimer', 'démence type alzheimer'] },
  { code: 'R56.8', label: 'Autres convulsions et non précisées', synonyms: ['convulsions', 'crise convulsive', 'crise d épilepsie'] },
  { code: 'R42', label: 'Étourdissements et sensation de vertige', synonyms: ['vertige', 'étourdissement', 'presyncope', 'vertige positionnel'] },

  /* --- Psychiatrie --- */
  { code: 'F20.9', label: 'Schizophrénie, sans précision', synonyms: ['schizophrenie', 'schizophrénie', 'psychose'] },
  { code: 'F31.9', label: 'Trouble bipolaire, sans précision', synonyms: ['bipolaire', 'trouble bipolaire', 'manie'] },
  { code: 'F12.9', label: 'Troubles liés au cannabis', synonyms: ['cannabis', 'consommation cannabis'] },

  /* --- Digestif --- */
  { code: 'K85.9', label: 'Pancréatite aiguë, sans précision', synonyms: ['pancreatite aigue', 'pancréatite aiguë', 'pancreatite'] },
  { code: 'K56.7', label: 'Iléus paroxystique', synonyms: ['ileus', 'iléus', 'occlusion fonctionnelle'] },
  { code: 'K56.5', label: 'Occlusion intestinale par bride', synonyms: ['occlusion intestinale', 'brides', 'syndrome subocclusif'] },
  { code: 'K51.9', label: 'Rectocolite hémorragique, sans précision', synonyms: ['rectocolite hemorragique', 'rch', 'colite ulcereuse'] },
  { code: 'K50.9', label: 'Maladie de Crohn, sans précision', synonyms: ['crohn', 'maladie crohn', 'mic'] },
  { code: 'K74.6', label: 'Cirrhose du foie et fibrose hépatique', synonyms: ['cirrhose', 'cirrhose hepatique', 'fibrose hepatique'] },
  { code: 'K70.4', label: 'Insuffisance hépatique chronique', synonyms: ['insuffisance hepatique', 'insuffisance hepatique chronique'] },
  { code: 'R17', label: 'Ictère, sans précision', synonyms: ['ictere', 'ictère', 'jaunisse'] },

  /* --- Rénal / uro --- */
  { code: 'N13.2', label: 'Hydronéphrose avec obstruction', synonyms: ['hydronephrose', 'dilatation pyelocalicielle'] },
  { code: 'N20.0', label: 'Calcul du rein', synonyms: ['calcul renal', 'lithiase renale', 'nephrolithiase'] },
  { code: 'N00.9', label: 'Syndrome néphritique aigu, sans précision', synonyms: ['glomerulonephrite aigue', 'glomerulonephrite aiguë', 'syndrome nephritique aigu'] },
  { code: 'R80', label: 'Protéinurie isolée', synonyms: ['proteinurie', 'protéinurie', 'albuminurie'] },

  /* --- Hématologie --- */
  { code: 'D68.9', label: 'Anomalie de la coagulation, sans précision', synonyms: ['trouble coagulation', 'coagulopathie', 'tp allonge'] },
  { code: 'D65', label: 'Coagulation intravasculaire disséminée', synonyms: ['civd', 'dic', 'coagulation intravasculaire disseminee'] },
  { code: 'D69.3', label: 'Purpura thrombopénique idiopathique', synonyms: ['pti', 'thrombopenie immune', 'thrombopénie'] },
  { code: 'C91.0', label: 'Leucémie lymphoïde aiguë', synonyms: ['lla', 'leucemie aigue lymphoblastique'] },

  /* --- Infectieux --- */
  { code: 'A15.9', label: 'Tuberculose respiratoire sans précision', synonyms: ['tuberculose', 'tb pulmonaire', 'bacille de koch'] },
  { code: 'B37.9', label: 'Candidose, sans précision', synonyms: ['candidose', 'candida', 'mycose invasive'] },
  { code: 'A49.9', label: 'Infection bactérienne, sans précision', synonyms: ['infection bacterienne', 'bacteriemie', 'bactériémie'] },
  { code: 'B99', label: 'Autres maladies infectieuses', synonyms: ['infection nosocomiale', 'surinfection'] },

  /* --- ORL / pneumo --- */
  { code: 'J03.9', label: 'Amygdalite aiguë, sans précision', synonyms: ['angine', 'amygdalite', 'mal de gorge infectieux'] },
  { code: 'J02.9', label: 'Pharyngite aiguë, sans précision', synonyms: ['pharyngite', 'rhinopharyngite infectieuse'] },
  { code: 'J12.9', label: 'Pneumonie virale, sans précision', synonyms: ['pneumonie virale', 'pneumopathie virale'] },
  { code: 'J69.0', label: 'Pneumopathie due à l’aspiration', synonyms: ['pneumopathie aspiration', 'fausse route', 'inhalation'] },
  { code: 'J90', label: 'Épanchement pleural non classé ailleurs', synonyms: ['epanchement pleural', 'épanchement pleural', 'pleuresie', 'pleurésie'] },
  { code: 'J93.1', label: 'Pneumothorax spontané', synonyms: ['pneumothorax', 'pneumothorax spontane'] },

  /* --- Métabolisme / autres --- */
  { code: 'E87.2', label: 'Acidose', synonyms: ['acidose', 'acidose metabolique', 'ph bas'] },
  { code: 'E87.3', label: 'Alcalose', synonyms: ['alcalose', 'ph eleve'] },
  { code: 'T88.7', label: 'Effet indésirable médicamenteux non classé', synonyms: ['effet indesirable', 'effet secondaire medicamenteux', 'Allergie medicamenteuse'] },

  /* --- Obstétrique / gynéco (codes courants) --- */
  { code: 'O80', label: 'Accouchement unique spontané', synonyms: ['accouchement', 'grossesse terme', 'delivrance'] },
  { code: 'O14.9', label: 'Hypertension gravidique avec protéinurie significative', synonyms: ['pre eclampsie', 'prééclampsie', 'eclampsie', 'hellp'] },
  { code: 'O99.6', label: 'Maladies du système nerveux compliquant grossesse', synonyms: ['grossesse pathologique'] },
  { code: 'N73.9', label: 'Maladie inflammatoire pelvienne féminine', synonyms: ['salpingite', 'infection pelvienne', 'sipaf'] },

  /* --- Pédiatrie / général --- */
  { code: 'R62.9', label: 'Retard de développement physiologique, sans précision', synonyms: ['retard croissance', 'retard staturo ponderal'] },
  { code: 'P07.3', label: 'Autre prématurité', synonyms: ['prematurite', 'prématurité', 'nouveau ne premature'] },
  { code: 'K90.0', label: 'Malabsorption cœliaque', synonyms: ['maladie coeliaque', 'cœliaque', 'gluten'] },

  /* --- Ortho / traumato --- */
  { code: 'M16.9', label: 'Coxarthrose, sans précision', synonyms: ['coxarthrose', 'arthrose hanche'] },
  { code: 'S06.9', label: 'Traumatisme crânien, sans précision', synonyms: ['tcc', 'traumatisme cranien', 'commotion cerebrale', 'commotion cérébrale'] },
  { code: 'T81.4', label: 'Infection liée à une procédure', synonyms: ['infection du site operatoire', 'infection post operatoire'] },

  /* --- Z / suivi --- */
  { code: 'Z51.5', label: 'Soins palliatifs', synonyms: ['soins palliatifs', 'palliatif'] },
  { code: 'Z08', label: 'Suivi après traitement pour tumeur maligne', synonyms: ['suivi cancer', 'surveillance oncologique'] },
  { code: 'Z92.1', label: 'Antécédents personnels d’usage de médicaments anticoagulants', synonyms: ['sous anticoagulant', 'anticoagulation'] },
];
